import datetime
a=datetime.datetime.now()
print(a)
print(a.strftime("%A"))
print(a.strftime("%a"))
print(a.strftime("%B"))
print(a.strftime("%b"))
print(a.strftime("%m"))
print(a.strftime("%d"))
print(a.strftime("%Y"))
print(a.strftime("%y"))
print(a.strftime("%D"))
print(a.strftime("%H"))
print(a.strftime("%I"))
print(a.strftime("%M"))
print(a.strftime("%S"))
print(a.strftime("%f"))
print(a.strftime("%p"))
print(a.strftime("%j"))
print(a.strftime("%X"))

b=datetime.datetime(2003,2,9)
print(b.strftime("%A"))